name: Go Code Quality and Security Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run Staticcheck
      run: staticcheck ./...

    - name: Run Go Vet
      run: go vet ./...

    - name: Install and Run GoSec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...
